### PR TITLE
Expanded build instructions

### PR DESCRIPTION
**Pull request by dfedorov-solace**
Signed-off-by: Dmitri Fedorov <dfedorov.solace@gmail.com>

### CODE REVIEW

**Comment by dfedorov-solace** [comment]
Gents, please review this change for build instructions @jschabowsky @mdspielman

**Comment by dfedorov-solace** [comment]
@jschabowsky @mdspielman all ready

**Comment by jschabowsky** [comment]
Looks good! I think we are good to merge and if we find something after that, we can always do a quick update.

**Comment by dfedorov-solace** [comment]
Thank you Jonathan

**Pull request merged**
